#13 번역
mingrammer/system-design-primer pull request #37
Opened 2018-07-22 13:15 UTC by ujuc

2018-07-23 05:29 UTC, mingrammer requested changes

2018-07-24 12:34 UTC, ujuc commented on README-kr.md
> +새로운 시스템을 디자인합니까?
다나까로 끝내다보니... 음. 비슷하게 수정해야겠네요.

2018-07-24 12:39 UTC, ujuc commented on README-kr.md
> +* **가용성** vs **일반성**
수정했습니다.

2018-07-24 12:39 UTC, ujuc commented on README-kr.md
> +다음으로 높은 수준의 절충 사항을 살펴본다:
수정완료!

2018-07-25 13:52 UTC, malkoG commented
어조는 각 챕터마다 달라도 상관없을까요....

2018-07-26 01:21 UTC, mingrammer commented
어조는 통일하는게 좋을 것 같습니다. 어차피 다 되면 다 읽어보면서 맞춰야해서 ..

2021-05-17 06:00 UTC, closed without merging